### ISSUE TITLE
Consider using Docker tags for versions

### ISSUE THREAD

**Issue by JonathonReinhart** [cdrx/docker-pyinstaller#13]
Many popular Docker images use tags for versioning their images, e.g. `debian:8.2`. In fact, I think versioning is the main purpose of tags.

However, there are lots of projects that seem to use them instead as sub-projects, e.g. `cdrx/pyinstaller-linux:python2` and cdrx/pyinstaller-linux:python3`.

My suggestion would be to change how you publish your Docker images, e.g.:
- `cdrx/pyinstaller-linux-py2:1.0`
- `cdrx/pyinstaller-linux-py3:1.0`

In this way, one would be able to pin to a specific version if needed. Cheers!

**Comment by cdrx** [comment]
I think this makes sense for versioned projects with distinct releases, like Debian, but for this project less so as there shouldn't be any breaking changes to the interface (except updating to the latest pyinstaller)

You can pin a particular version of pyinstaller with requirements.txt

**Comment by bmustiata** [comment]
Actually that's not 100% true. For example right now the windows version for 3.6 generates binaries that fail with a dll exception. Binaries must be stable as well for stable builds. 

I remember it working for 3.5. 

The whole point of the tags is to guarantee runs. I did a docker pull, and found myself not being able to build anymore, nor revert to a working version.

In docker it is possible to run automatic builds for tags as well.

**Comment by cdrx** [comment]
:(

What error do you get @bmustiata ?

**Comment by bmustiata** [comment]
Right now I'm not near my computer, but it was a very cryptic error message
that after some Google meant that I don't have VS 2015 redistributable
package installed on my host (the host is the IE11 Virtual Machine, from
modern.ie).

The code is python 2.7 compatible, and the build with that one yields an
executable that doesn't require the redistributable package.

I'll try to investigate it these days since I want to code from now on only
in 3.6, but you should use tags imho.

On Dec 15, 2017 17:55, "Chris R" <notifications@github.com> wrote:

:(

What error do you get @bmustiata <https://github.com/bmustiata> ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cdrx/docker-pyinstaller/issues/13#issuecomment-352056125>,
or mute the thread

**Comment by bmustiata** [comment]
This is the error I get when running it. Note that this is a 32 bit machine, so I needed to change the Docker build file a bit.

![image](https://user-images.githubusercontent.com/457866/34084741-c14d7376-e385-11e7-8c77-71c29cd9b6ce.png)
