### ISSUE TITLE
Has something changed since the Jenkins tutorial?

### ISSUE THREAD

**Issue by djotaku** [cdrx/docker-pyinstaller#52]
I'm following these instructions: https://jenkins.io/doc/tutorials/build-a-python-app-with-pyinstaller/ with the difference being that I am using the python3 instead of python2 and, obviously that the name of my python file is different. 

You can see at: https://github.com/djotaku/ELDonationTracker/blob/devel/JenkinsFile

The error I'm getting is: 

```
+ pyinstaller --onefile extralifedonations.py

/var/jenkins_home/workspace/extralifedonationtracker@tmp/durable-38d45fbf/script.sh: 1: /var/jenkins_home/workspace/extralifedonationtracker@tmp/durable-38d45fbf/script.sh: pyinstaller: not found

script returned exit code 127
```

Has something changed since they wrote that tutorial? Or is something different with Py3 or something?

Thanks!

**Comment by djotaku** [comment]
So if I change "steps" to 

 sh ''

Jenkins stops complaining, but nothing runs and I don't get a binary.

**Comment by djotaku** [comment]
Here's what the pipeline.log contains:
```

[Pipeline] withEnv
[Pipeline] {
[Pipeline] sh
+ docker inspect -f . cdrx/pyinstaller-linux:python3
.
[Pipeline] withDockerContainer
Jenkins seems to be running inside container 7425a4d1ee8a9dbf06ad189d97bc1914aa5e8187246ba901d88dba8d4ea1b7a2
$ docker run -t -d -u 0:0 -w /var/jenkins_home/workspace/extralifedonationtracker --volumes-from 7425a4d1ee8a9dbf06ad189d97bc1914aa5e8187246ba901d88dba8d4ea1b7a2 -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** cdrx/pyinstaller-linux:python3 cat
$ docker top d7f1e992b70d59cb4fee891e933d8228f93c4cfaf65d6435e6d24437c4f3618b -eo pid,comm
ERROR: The container started but didn't run the expected command. Please double check your ENTRYPOINT does execute the command passed as docker run argument, as required by official docker images (see https://github.com/docker-library/official-images#consistency for entrypoint consistency requirements).
Alternatively you can force image entrypoint to be disabled by adding option `--entrypoint=''`.
[Pipeline] {
[Pipeline] sh
Post stage
[Pipeline] archiveArtifacts
Archiving artifacts
[Pipeline] }
$ docker stop --time=1 d7f1e992b70d59cb4fee891e933d8228f93c4cfaf65d6435e6d24437c4f3618b
$ docker rm -f d7f1e992b70d59cb4fee891e933d8228f93c4cfaf65d6435e6d24437c4f3618b
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by cdrx** [comment]
Possibly related to #38

I think this may be something to do with the entry point being overwritten, but I've never used Jenkins so not sure how it works.

Will leave this open for now incase any jenkins experts spot this issue...

**Comment by majusmisiak** [comment]
@djotaku what Jenkins is doing here is running container in background mode with `cat` command. Then before any command is run within the container it does sanity check, whether `cat` [ps is actually running within the container namespace](https://github.com/jenkinsci/docker-workflow-plugin/blob/f0c60a55c205dc945619f18ae7b4bfd9be401e26/src/main/java/org/jenkinsci/plugins/docker/workflow/WithContainerStep.java#f060a5L188).

When you have container with entrypoint set, it is a bit tricky and behaves differently between `docker-pipeline-plugin` versions. Since version `1.9` of that plugin, entrypoint is not respected - [JENKINS-41316](https://issues.jenkins-ci.org/browse/JENKINS-41316) - so your attempt would work. In your case, since there is already entrypoint in pyinstaller-linux docker image, it will fail, because `/entrypoint.sh` script is what really gets run. 

Ok, so what can you do to solve that:

- upgrade docker pipeline plugin to >=1.9 - simple but may break stuff for other people using same Jenkins server
- run this docker image as it was intended by @cdrx  - instead of docker inside use shell as in `sh "docker run -v $(pwd -P):/src cdxr/pyinstaller...`
- most proper way in my opinion - derive your own docker image starting with `FROM cdxr/pyinstaller-linux:python3` and then apply whatever customizations you need to entrypoint / command

**Comment by djotaku** [comment]
Thanks for the info. It looks like there are still complaints that it's not fixed even though Jenkins folks consider it fixed. I'm going to go with your third option. If there's a way to close this ticket while still having it be searchable by others who are following the Jenkins Python Pipeline tutorial, that would be best.

**Comment by Mediterranean90** [comment]
Have you solved this problem?
